### ISSUE TITLE
Please change the project name

### ISSUE THREAD

**Issue by alecthegeek** [Rafe/papercut#10] opened 2014-06-26 03:49 UTC
Awesome project!

Please can you change name as "PaperCut" is a registered trade mark of @papercutsoftware

Many thanks

**Comment by dkushner** [comment] 2014-07-08 18:02
Obviously I'm not the repo owner here, @alecthegeek, but there's absolutely no way this project could be considered infringing on that mark. For one, this product is free to use, has nothing to do with print services and makes no mention of/reference to the allegedly infringed mark.

**Comment by kennethklee** [comment] 2014-08-11 19:27
:-1:

**Comment by SocialPaperCut** [comment] 2014-08-12 02:21
Hi Jimmy
One of our project team came across your great project to resize and crop pics. Our devs at PaperCut Software also contribute to GitHub, which is why the Trade Mark issue was brought to our attention. The name and words are an International Trade Mark and as we are also on the same site, it could confuse users as to what kind of tools are from our devs if the same name is being used. If you can kindly change the project name, this will avoid any confusion. Many thanks.

**Comment by Rafe** [comment] 2014-08-12 03:35
Hi SocialPaperCut and alecthegeek,

Sorry for late reply,

I can't see this project 'papercut' will create confusion with 'PaperCut Software'.
Can you provide any example or open source project that PaperCut Software created which might makes developer confuse?

Also I just did a github search for all projects named 'papercut', there are 11 projects with the same name. For reducing the confusion with your trademark, I suggest you can also contact the owners
to change their project name.

I will just close this issue before any of those things happened.

**Closed as completed by Rafe** 2014-08-12 03:35 UTC

**Comment by SocialPaperCut** [comment] 2014-08-12 03:57
Thank you Jimmy, we will contact the others too.

**Comment by codedance** [comment] 2014-08-13 13:51
Hi Raf,

Apologies for jumping in on this late.  I’m the founder at PaperCut, and also lead and contribute to a number of open source projects on GitHub.  When I do get to code (which is unfortunately limited to after-hours work lately), it’s mostly open source projects I’m passionate about.  These range from security projects like [GhostTrap](https://github.com/PaperCutSoftware/GhostTrap), through to jQuery [plugins](https://github.com/codedance/jquery.AreYouSure), and most recently my passion has been around Go (sorry... skipped node :-).

At PaperCut, trademark issues do come up now and then. Recently our [Teleportme](http://papercutsoftware.github.io/teleportme/) project ran into a similar conflict.  Originally it was called Telectroscope and this name clashed with a commercial modern art project in London and New York.  The artist who owned the trademark reached out to us and brought in the lawyers.  Like you, we also thought there was little room for confusion, but agreed to change.  Preferring to work directly with the artist we reached out and asked if he could help us come up with a new name!  He agreed and together we brainstormed to create a new name and a great story behind it.

In this case I suppose the tables are now turned and we seem to be on the other side of the conversation. :-( Darn!  We don’t much like it, but we’re [required to protect our mark](http://en.wikipedia.org/wiki/Trademark#Maintaining_rights). I agree with you that it’s very unlikely that a small coffee script project would be confused with PaperCut print management software.  It would be more of a question of dilution.  I am all too aware of the pain of renaming repos, API impact, file names, etc. having coordinated this on Teleportme, so I have some creative/lateral alternatives and would like to run these by you.  I’ll shoot you a direct email.

**Comment by dkushner** [comment] 2014-08-21 01:05
@codedance, I'm not involved with the team (or individual as it would appear) that is developing this library, but it would appear even to _me_ that you have absolutely zero evidence of infringement.

The courts have an established criteria for quantifying consumer confusion that might be caused by an infringing mark, so let's review those real quick:

**Strength of the mark**
The name "PaperCut" is an arbitrary mark, meaning that it is simply a word in common usage that has no direct bearing on the products you provide. The actual "strength" of the mark will be substantiated by a court but arbitrary marks in general are considerably weaker than proprietary or coined ones. 

**Proximity of the goods**
It appears to me the only measurable degree of proximity these two marks share is that they are both software. To my knowledge their function is _entirely_ disparate. Can you quantify the proximity more clearly?

**Similarity of the marks**
Your website features a figurative mark of entirely different styling, capitalization and coloration. Not even remotely infringed upon by the use of the common word 'papercut' in an entirely different font.

**Evidence of actual confusion**
I would be absolutely stunned if you were to present any sort of verifiable evidence of this.

**Marketing channels used**
This is actually one of the weakest elements involved in determining the likelihood of confusion since it has recently been downplayed by a Ninth Circuit court ruling. Even so, its pretty obvious to anyone that none of the same marketing channels were used by the competing marks.

**Type of goods and the degree of care likely to be exercised by the purchaser**
That these are two entirely different products hardly even bears mentioning. You provide a pre-packaged print management solution targeted at enterprise clients and businesses. This project is a source-distributed library targeted at node.js developers. I would absolutely love to see your attorney's brief regarding how a customer might accidentally stumble upon this repository and confuse it for your product. The Ninth Circuit recently struck down the "everyone on the internet is an idiot" precedent that had previously been applied to cases of infringement in e-commerce, so you may have a tough time.

**Defendant's intent in selecting the mark**
Yeah, I don't think this needs to be addressed. There's absolutely no evidence that @Rafe was even aware your company existed at the time he made this repository.

**Likelihood of expansion of the product lines**
You know, we'll probably have to ask @Rafe if he intends on releasing a wide array of node.js libraries under his lucrative 'papercut' brand name, but somehow I doubt it.

I appreciate the whole coy act but what you're doing is nothing short of petty bullying. It was very considerate of your company to negotiate a mutually agreeable resolution to your other infringement issues but its pretty obvious to anyone that actually looked up the [telectroscope](http://en.wikipedia.org/wiki/Telectroscope) that your product had some concerning similarities in function. I can say, "this product allows you to be seen remotely and to see others remotely through a display" and a consumer might reasonably be confused between the two marks. Are you honestly suggesting that the same can be said about this project?

It's great that you contribute to open source projects, I too have an immense appreciation for the quantity and quality of work that people like @Rafe put in just to make other developer's lives a little easier. He makes no money off of this project or the allegedly infringing mark, as you should know as an open source contributor. The fact that you're posturing like this and pretending you have some sort of legal obligation to threaten legal action against an independent project with such fantastically tenuous links to your company reflects poorly on you and on the organization you claim to be protecting.
